
interface _GlobalComponents {
      'AppFooter': typeof import("../components/app/footer.vue")['default']
    'AppHeader': typeof import("../components/app/header.vue")['default']
    'BaseNavigation': typeof import("../components/base/Navigation.vue")['default']
    'BaseRainbowButton': typeof import("../components/base/RainbowButton.vue")['default']
    'BaseContactForm': typeof import("../components/base/contactForm.vue")['default']
    'SectionAreasScreen': typeof import("../components/section/AreasScreen.vue")['default']
    'SectionContactsScreen': typeof import("../components/section/ContactsScreen.vue")['default']
    'SectionFifthScreen': typeof import("../components/section/FifthScreen.vue")['default']
    'SectionFirstScreen': typeof import("../components/section/FirstScreen.vue")['default']
    'SectionFourthScreen': typeof import("../components/section/FourthScreen.vue")['default']
    'SectionMadeInRussiaScreen': typeof import("../components/section/MadeInRussiaScreen.vue")['default']
    'SectionSecondScreen': typeof import("../components/section/SecondScreen.vue")['default']
    'SectionServiceScreen': typeof import("../components/section/ServiceScreen.vue")['default']
    'SectionSoftScreen': typeof import("../components/section/SoftScreen.vue")['default']
    'SectionThirdScreen': typeof import("../components/section/ThirdScreen.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'Accordion': typeof import("../components/ui/accordion/index")['Accordion']
    'AccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'AccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'AccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'Carousel': typeof import("../components/ui/carousel/index")['Carousel']
    'CarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'CarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'CarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'CarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'CarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'Form': typeof import("../components/ui/form/index")['Form']
    'FormField': typeof import("../components/ui/form/index")['FormField']
    'FormItem': typeof import("../components/ui/form/index")['FormItem']
    'FormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'FormControl': typeof import("../components/ui/form/index")['FormControl']
    'FormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'FormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'FORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Menubar': typeof import("../components/ui/menubar/index")['Menubar']
    'MenubarCheckboxItem': typeof import("../components/ui/menubar/index")['MenubarCheckboxItem']
    'MenubarContent': typeof import("../components/ui/menubar/index")['MenubarContent']
    'MenubarGroup': typeof import("../components/ui/menubar/index")['MenubarGroup']
    'MenubarItem': typeof import("../components/ui/menubar/index")['MenubarItem']
    'MenubarLabel': typeof import("../components/ui/menubar/index")['MenubarLabel']
    'MenubarMenu': typeof import("../components/ui/menubar/index")['MenubarMenu']
    'MenubarRadioGroup': typeof import("../components/ui/menubar/index")['MenubarRadioGroup']
    'MenubarRadioItem': typeof import("../components/ui/menubar/index")['MenubarRadioItem']
    'MenubarSeparator': typeof import("../components/ui/menubar/index")['MenubarSeparator']
    'MenubarShortcut': typeof import("../components/ui/menubar/index")['MenubarShortcut']
    'MenubarSub': typeof import("../components/ui/menubar/index")['MenubarSub']
    'MenubarSubContent': typeof import("../components/ui/menubar/index")['MenubarSubContent']
    'MenubarSubTrigger': typeof import("../components/ui/menubar/index")['MenubarSubTrigger']
    'MenubarTrigger': typeof import("../components/ui/menubar/index")['MenubarTrigger']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'Textarea': typeof import("../components/ui/textarea/index")['Textarea']
    'Toaster': typeof import("../components/ui/toast/index")['Toaster']
    'Toast': typeof import("../components/ui/toast/index")['Toast']
    'ToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'ToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'ToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'ToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'ToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'ToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAppFooter': typeof import("../components/app/footer.vue")['default']
    'LazyAppHeader': typeof import("../components/app/header.vue")['default']
    'LazyBaseNavigation': typeof import("../components/base/Navigation.vue")['default']
    'LazyBaseRainbowButton': typeof import("../components/base/RainbowButton.vue")['default']
    'LazyBaseContactForm': typeof import("../components/base/contactForm.vue")['default']
    'LazySectionAreasScreen': typeof import("../components/section/AreasScreen.vue")['default']
    'LazySectionContactsScreen': typeof import("../components/section/ContactsScreen.vue")['default']
    'LazySectionFifthScreen': typeof import("../components/section/FifthScreen.vue")['default']
    'LazySectionFirstScreen': typeof import("../components/section/FirstScreen.vue")['default']
    'LazySectionFourthScreen': typeof import("../components/section/FourthScreen.vue")['default']
    'LazySectionMadeInRussiaScreen': typeof import("../components/section/MadeInRussiaScreen.vue")['default']
    'LazySectionSecondScreen': typeof import("../components/section/SecondScreen.vue")['default']
    'LazySectionServiceScreen': typeof import("../components/section/ServiceScreen.vue")['default']
    'LazySectionSoftScreen': typeof import("../components/section/SoftScreen.vue")['default']
    'LazySectionThirdScreen': typeof import("../components/section/ThirdScreen.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'LazyAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'LazyAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'LazyAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyCarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'LazyCarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyCarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyCarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyCarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyCarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyForm': typeof import("../components/ui/form/index")['Form']
    'LazyFormField': typeof import("../components/ui/form/index")['FormField']
    'LazyFormItem': typeof import("../components/ui/form/index")['FormItem']
    'LazyFormLabel': typeof import("../components/ui/form/index")['FormLabel']
    'LazyFormControl': typeof import("../components/ui/form/index")['FormControl']
    'LazyFormMessage': typeof import("../components/ui/form/index")['FormMessage']
    'LazyFormDescription': typeof import("../components/ui/form/index")['FormDescription']
    'LazyFORMITEMINJECTIONKEY': typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyMenubar': typeof import("../components/ui/menubar/index")['Menubar']
    'LazyMenubarCheckboxItem': typeof import("../components/ui/menubar/index")['MenubarCheckboxItem']
    'LazyMenubarContent': typeof import("../components/ui/menubar/index")['MenubarContent']
    'LazyMenubarGroup': typeof import("../components/ui/menubar/index")['MenubarGroup']
    'LazyMenubarItem': typeof import("../components/ui/menubar/index")['MenubarItem']
    'LazyMenubarLabel': typeof import("../components/ui/menubar/index")['MenubarLabel']
    'LazyMenubarMenu': typeof import("../components/ui/menubar/index")['MenubarMenu']
    'LazyMenubarRadioGroup': typeof import("../components/ui/menubar/index")['MenubarRadioGroup']
    'LazyMenubarRadioItem': typeof import("../components/ui/menubar/index")['MenubarRadioItem']
    'LazyMenubarSeparator': typeof import("../components/ui/menubar/index")['MenubarSeparator']
    'LazyMenubarShortcut': typeof import("../components/ui/menubar/index")['MenubarShortcut']
    'LazyMenubarSub': typeof import("../components/ui/menubar/index")['MenubarSub']
    'LazyMenubarSubContent': typeof import("../components/ui/menubar/index")['MenubarSubContent']
    'LazyMenubarSubTrigger': typeof import("../components/ui/menubar/index")['MenubarSubTrigger']
    'LazyMenubarTrigger': typeof import("../components/ui/menubar/index")['MenubarTrigger']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTextarea': typeof import("../components/ui/textarea/index")['Textarea']
    'LazyToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppFooter: typeof import("../components/app/footer.vue")['default']
export const AppHeader: typeof import("../components/app/header.vue")['default']
export const BaseNavigation: typeof import("../components/base/Navigation.vue")['default']
export const BaseRainbowButton: typeof import("../components/base/RainbowButton.vue")['default']
export const BaseContactForm: typeof import("../components/base/contactForm.vue")['default']
export const SectionAreasScreen: typeof import("../components/section/AreasScreen.vue")['default']
export const SectionContactsScreen: typeof import("../components/section/ContactsScreen.vue")['default']
export const SectionFifthScreen: typeof import("../components/section/FifthScreen.vue")['default']
export const SectionFirstScreen: typeof import("../components/section/FirstScreen.vue")['default']
export const SectionFourthScreen: typeof import("../components/section/FourthScreen.vue")['default']
export const SectionMadeInRussiaScreen: typeof import("../components/section/MadeInRussiaScreen.vue")['default']
export const SectionSecondScreen: typeof import("../components/section/SecondScreen.vue")['default']
export const SectionServiceScreen: typeof import("../components/section/ServiceScreen.vue")['default']
export const SectionSoftScreen: typeof import("../components/section/SoftScreen.vue")['default']
export const SectionThirdScreen: typeof import("../components/section/ThirdScreen.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const Accordion: typeof import("../components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const Carousel: typeof import("../components/ui/carousel/index")['Carousel']
export const CarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const CarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const CarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const CarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Form: typeof import("../components/ui/form/index")['Form']
export const FormField: typeof import("../components/ui/form/index")['FormField']
export const FormItem: typeof import("../components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const FormControl: typeof import("../components/ui/form/index")['FormControl']
export const FormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const FormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const FORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Menubar: typeof import("../components/ui/menubar/index")['Menubar']
export const MenubarCheckboxItem: typeof import("../components/ui/menubar/index")['MenubarCheckboxItem']
export const MenubarContent: typeof import("../components/ui/menubar/index")['MenubarContent']
export const MenubarGroup: typeof import("../components/ui/menubar/index")['MenubarGroup']
export const MenubarItem: typeof import("../components/ui/menubar/index")['MenubarItem']
export const MenubarLabel: typeof import("../components/ui/menubar/index")['MenubarLabel']
export const MenubarMenu: typeof import("../components/ui/menubar/index")['MenubarMenu']
export const MenubarRadioGroup: typeof import("../components/ui/menubar/index")['MenubarRadioGroup']
export const MenubarRadioItem: typeof import("../components/ui/menubar/index")['MenubarRadioItem']
export const MenubarSeparator: typeof import("../components/ui/menubar/index")['MenubarSeparator']
export const MenubarShortcut: typeof import("../components/ui/menubar/index")['MenubarShortcut']
export const MenubarSub: typeof import("../components/ui/menubar/index")['MenubarSub']
export const MenubarSubContent: typeof import("../components/ui/menubar/index")['MenubarSubContent']
export const MenubarSubTrigger: typeof import("../components/ui/menubar/index")['MenubarSubTrigger']
export const MenubarTrigger: typeof import("../components/ui/menubar/index")['MenubarTrigger']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const Textarea: typeof import("../components/ui/textarea/index")['Textarea']
export const Toaster: typeof import("../components/ui/toast/index")['Toaster']
export const Toast: typeof import("../components/ui/toast/index")['Toast']
export const ToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const ToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const ToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const ToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const ToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const ToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAppFooter: typeof import("../components/app/footer.vue")['default']
export const LazyAppHeader: typeof import("../components/app/header.vue")['default']
export const LazyBaseNavigation: typeof import("../components/base/Navigation.vue")['default']
export const LazyBaseRainbowButton: typeof import("../components/base/RainbowButton.vue")['default']
export const LazyBaseContactForm: typeof import("../components/base/contactForm.vue")['default']
export const LazySectionAreasScreen: typeof import("../components/section/AreasScreen.vue")['default']
export const LazySectionContactsScreen: typeof import("../components/section/ContactsScreen.vue")['default']
export const LazySectionFifthScreen: typeof import("../components/section/FifthScreen.vue")['default']
export const LazySectionFirstScreen: typeof import("../components/section/FirstScreen.vue")['default']
export const LazySectionFourthScreen: typeof import("../components/section/FourthScreen.vue")['default']
export const LazySectionMadeInRussiaScreen: typeof import("../components/section/MadeInRussiaScreen.vue")['default']
export const LazySectionSecondScreen: typeof import("../components/section/SecondScreen.vue")['default']
export const LazySectionServiceScreen: typeof import("../components/section/ServiceScreen.vue")['default']
export const LazySectionSoftScreen: typeof import("../components/section/SoftScreen.vue")['default']
export const LazySectionThirdScreen: typeof import("../components/section/ThirdScreen.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const LazyAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const LazyAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const LazyAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyCarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const LazyCarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyCarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyCarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyCarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyCarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyForm: typeof import("../components/ui/form/index")['Form']
export const LazyFormField: typeof import("../components/ui/form/index")['FormField']
export const LazyFormItem: typeof import("../components/ui/form/index")['FormItem']
export const LazyFormLabel: typeof import("../components/ui/form/index")['FormLabel']
export const LazyFormControl: typeof import("../components/ui/form/index")['FormControl']
export const LazyFormMessage: typeof import("../components/ui/form/index")['FormMessage']
export const LazyFormDescription: typeof import("../components/ui/form/index")['FormDescription']
export const LazyFORMITEMINJECTIONKEY: typeof import("../components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyMenubar: typeof import("../components/ui/menubar/index")['Menubar']
export const LazyMenubarCheckboxItem: typeof import("../components/ui/menubar/index")['MenubarCheckboxItem']
export const LazyMenubarContent: typeof import("../components/ui/menubar/index")['MenubarContent']
export const LazyMenubarGroup: typeof import("../components/ui/menubar/index")['MenubarGroup']
export const LazyMenubarItem: typeof import("../components/ui/menubar/index")['MenubarItem']
export const LazyMenubarLabel: typeof import("../components/ui/menubar/index")['MenubarLabel']
export const LazyMenubarMenu: typeof import("../components/ui/menubar/index")['MenubarMenu']
export const LazyMenubarRadioGroup: typeof import("../components/ui/menubar/index")['MenubarRadioGroup']
export const LazyMenubarRadioItem: typeof import("../components/ui/menubar/index")['MenubarRadioItem']
export const LazyMenubarSeparator: typeof import("../components/ui/menubar/index")['MenubarSeparator']
export const LazyMenubarShortcut: typeof import("../components/ui/menubar/index")['MenubarShortcut']
export const LazyMenubarSub: typeof import("../components/ui/menubar/index")['MenubarSub']
export const LazyMenubarSubContent: typeof import("../components/ui/menubar/index")['MenubarSubContent']
export const LazyMenubarSubTrigger: typeof import("../components/ui/menubar/index")['MenubarSubTrigger']
export const LazyMenubarTrigger: typeof import("../components/ui/menubar/index")['MenubarTrigger']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const LazyToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
