// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2024, 11:21:36 AM
const configMerger = require("/Users/belinovich/Desktop/web/labvision/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/belinovich/Desktop/web/labvision/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/plugins/**/*.{js,ts,mjs}","/Users/belinovich/Desktop/web/labvision/composables/**/*.{js,ts,mjs}","/Users/belinovich/Desktop/web/labvision/utils/**/*.{js,ts,mjs}","/Users/belinovich/Desktop/web/labvision/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/belinovich/Desktop/web/labvision/app.config.{js,ts,mjs}"] }));

module.exports = config
